
# Tipos de gupros musculares
GrupoMuscular(superiores)
GrupoMuscular(inferiores)
GrupoMuscular(costas)
GrupoMuscular(peito)
GrupoMuscular(abdomen)

# Nível de cada exercício
Nivel("flexao plantar", iniciante)
Nivel("agachamento", iniciante)
Nivel("stiff", iniciante)
Nivel("cadeira extensora", iniciante)
Nivel("panturrilha sentado", iniciante)
Nivel("leg press", iniciante)
Nivel("elevacao lateral", iniciante)
Nivel("rosca direta", iniciante)
Nivel("rosca martelo", iniciante)
Nivel("triceps corda", iniciante)
Nivel("triceps na barra", iniciante)
Nivel("flexao de bracos", iniciante)
Nivel("remada articulada", iniciante)
Nivel("supino reto", iniciante)
Nivel("puxada frontal", iniciante)
Nivel("supino vertical", iniciante)
Nivel("pull down", iniciante)
Nivel("leg press", intermediario)
Nivel("agachamento na barra", intermediario)
Nivel("cadeira extensora", intermediario)
Nivel("flexora deitado", intermediario)
Nivel("elevacao pelvica", intermediario)
Nivel("elevacao de panturrilha", intermediario)
Nivel("desenvolvimento", intermediario)
Nivel("scott", intermediario)
Nivel("triceps corda", intermediario)
Nivel("meio terra", avancado)
Nivel("remada na maquina", avancado)
Nivel("rosca direta", intermediario)
Nivel("triceps no banco", intermediario)
Nivel("supino reto", intermediario)
Nivel("supino inclinado", intermediario)
Nivel("fly", intermediario)
Nivel("supino vertical", intermediario)
Nivel("crossover baixo", intermediario)
Nivel("prancha", intermediario)
Nivel("barra fixa", intermediario)
Nivel("puxada frontal", intermediario)
Nivel("serrote", intermediario)
Nivel("remada baixa", intermediario)
Nivel("fly invertido", intermediario)
Nivel("agachamento livre na barra", avancado)
Nivel("búlgaro", avancado)
Nivel("leg press", avancado)
Nivel("flexora deitado", avancado)
Nivel("elevacão pelvica", avancado)
Nivel("panturrilha sentado", avancado)
Nivel("21 na barra w", avancado)
Nivel("scott", avancado)
Nivel("rosca direta", avancado)
Nivel("triceps na barra w", avancado)
Nivel("triceps nas paralelas", avancado)
Nivel("triceps corda", avancado)
Nivel("remada alta", avancado)
Nivel("supino reto", avancado)
Nivel("crossover", avancado)
Nivel("supino declinado", avancado)
Nivel("crucifixo reto", avancado)
Nivel("abdominal na roda", avancado)
Nivel("puxada" frontal, avancado)
Nivel("serrote", avancado)
Nivel("remada cavalinho", avancado)

# Relaciona cada exercício com seu grupo muscular
Exercicio("flexão de bracos", peito)
Exercicio("supino reto", peito)
Exercicio("flexão plantar", inferiores)
Exercicio("agachamento", inferiores)
Exercicio("stiff", inferiores)
Exercicio("cadeira extensora", inferiores)
Exercicio("panturrilha sentado", inferiores)
Exercicio("leg press", inferiores)
Exercicio("agachamento na barra", inferiores)
Exercicio("flexora deitado", inferiores)
Exercicio("elevacão pelvica", inferiores)
Exercicio("elevacão de panturrilha", inferiores)
Exercicio("agachamento livre na barra", inferiores)
Exercicio("búlgaro", inferiores)
Exercicio("rosca direta", superiores)
Exercicio("rosca martelo", superiores)
Exercicio("scott", superiores)
Exercicio("21 na barra w", superiores)
Exercicio("triceps corda", superiores)
Exercicio("triceps na barra", superiores)
Exercicio("triceps no banco", superiores)
Exercicio("triceps na barra w", superiores)
Exercicio("triceps nas paralelas", superiores)
Exercicio("elevacão lateral", superiores)
Exercicio("desenvolvimento", superiores)
Exercicio("remada alta", superiores)
Exercicio("supino vertical", peito)
Exercicio("fly", peito)
Exercicio("supino inclinado", peito)
Exercicio("crossover baixo", peito)
Exercicio("crossover", peito)
Exercicio("supino declinado", peito)
Exercicio("crucifixo reto", peito)
Exercicio("remada articulada", costas)
Exercicio("puxada frontal", costas)
Exercicio("pull down", costas)
Exercicio("barra fixa", costas)
Exercicio("serrote", costas)
Exercicio("remada baixa", costas)
Exercicio("fly invertido", costas)
Exercicio("meio terra", costas)
Exercicio("remada na maquina", costas)
Exercicio("remada cavalinho", costas)
Exercicio("prancha", abdomen)
Exercicio("abdominal na roda", abdomen)

# Define o número de séries pra cada nível de dificuldade
Series(3, iniciante)
Series(3-4, intermediario)
Series(3-4, avancado)

# Define o número de repetições pra cada nível de dificuldade
Repeticoes(10-12, iniciante)
Repeticoes(8-12, intermediario)
Repeticoes(10-15, avancado)
Repeticoes(6-8, avancado)


